version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: netlify-cms
    versions:
    - 2.10.100
    - 2.10.105
    - 2.10.108
    - 2.10.109
    - 2.10.110
    - 2.10.111
    - 2.10.112
    - 2.10.114
    - 2.10.116
    - 2.10.85
    - 2.10.91
    - 2.10.92
    - 2.10.97
  - dependency-name: uswds
    versions:
    - 2.10.0
    - 2.10.1
    - 2.10.2
    - 2.10.3
    - 2.11.1
