engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "_sass/**/*"
exclude_paths:
- "lib/tasks/**"
- _sass/_libs/**/*
- _sass/_core/syntax-highlighting.scss
- assets/js/lib/**/*
- bin
- node_modules
- .bundle
- .sass-cache
