env: "development"

exclude:
- _pages
- _posts
- CONTRIBUTING.md
- README.md
- PULL_REQUEST_TEMPLATE.md
- ISSUE_TEMPLATE.md
- 'Accessibility Scanning Using Pa11y-ci.md'
- accessibility-scan
- api-endpoints
- build
- circle.yml
- docker-compse.yml
- docker_entrypoint.rb
- Dockerfile
- favicon.ico
- feed*
- Gemfile*
- humans.txt
- package.json
- robots.txt
- search-index*
- serve
- sitemap.xml
- system-security-plan.yml
