# get data from the hub
jekyll_get:
  - data: team
    json: 'https://18f.gsa.gov/hub/api/team/'
    cache: true
  - data: projects
    json: 'https://18f.gsa.gov/hub/api/projects/'
    cache: true
  - data: pif_team
    json: 'https://18f.gsa.gov/hub/api/pif_team/'
    cache: true
  - data: pif_projects
    json: 'https://18f.gsa.gov/hub/api/pif_projects/'
    cache: true
