env: "development"

exclude:
- _pages
- _posts
- _authors
- accessibility-scan
- api-endpoints
- build
- circle.yml
- docker-compse.yml
- docker_entrypoint.rb
- Dockerfile
- favicon.ico
- feed*
- Gemfile*
- humans.txt
- package.json
- robots.txt
- search-index*
- serve
- sitemap.xml
- system-security-plan.yml
