#!/bin/sh

npm run uswds-build && \ 
LC_ALL="en_US.UTF-8" \
bundle exec jekyll serve \
  --watch \
  --incremental \
  --host 0.0.0.0  \
  --baseurl /site \
  --trace \
  --config="_config.yml,_config-fast-builds.yml" \
& npm run uswds-watch \
