#!/bin/sh
# Run locally as `./serve-accesslint local`
set -e

ruby config_blog.rb

if [ -z "$1" ]
  then
    LC_ALL="en_US.UTF-8" \
    bundle exec jekyll serve \
      --detach \
      --baseurl /site \
      --host 0.0.0.0 \
      --config="_config.yml,_config-accesslint.yml"
  else
    LC_ALL="en_US.UTF-8" \
    bundle exec jekyll serve \
      --watch \
      --incremental \
      --baseurl /site \
      --host 0.0.0.0 \
      --config="_config.yml,_config-accesslint.yml"
      echo "serving site locally..."
fi
