-
  display: Delivery
  link: /dashboard
  description: "Delivery is at the heart of what we do. Our team of designers and developers work to transform government services by building world-class software products and raise standards of software development throughout the government. Learn more about our products by visiting our <a href='/dashboard'>dashboard</a> and you can find more information about <a href='https://pages.18f.gov/guides'>our standards and capabilities</a> through our guides."
  cta: <a href='/dashboard'>the ways we can help you at 18F Consulting</a>
-
  display: Consulting
  link: /consulting
  description: "Our Consulting team helps federal agencies deliver successful digital services by using proven, modern approaches to your work such as human-centered design, lean startup, and agile development. As consultants, we're your partners: rolling-up our sleeves right alongside you to solve the biggest challenges facing your agency. From developing agile acquisition strategies to evaluating opportunities to improving your digital initiatives, our team sets you up for success."
  cta: the ways we can help you at <a href='/consulting/'>18F Consulting</a>
-
  display: Join Us
  link: https://sites.18f.gov/joining-18f
  description: "We are looking for candidates passionate about our mission, with top notch software development, design, content, and operations skills to match. The majority of our team is distributed across the country, in places like Chicago, New York, Raleigh, Tucson, Austin, Dayton, Philadelphia, San Diego, Seattle, and Portland."
  cta: "<a href='https://sites.18f.gov/joining-18f'>joining our team</a>"