title: 18F Guides
description: >- # this means to ignore newlines
  A central resources for all 18F guides and methods

host: https://guides.18f.gov

# Twitter handle. Only the handle, not the URL.
twitter: 18F

dap:
  agency: GSA
  subagency: TTS

ga:
  ua: G-94QF2Z1S0G

# Search.gov configuration
#
# TODO
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:

  # Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
  endpoint: https://search.usa.gov

  # Replace this with your search.gov account.
  affiliate: 18f-guides

  # Replace this with your access key.
  access_key: empty

  # This renders the results within the page instead of sending to user to search.gov.
  inline: false

  # This allows Search.gov to present relevant type-ahead search suggestions in your website's search box.
  # If you do not want to present search suggestions, set this value to false.
  suggestions: false

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################
