project:
  text: Projects
  permalink: /what-we-deliver/
  collections: ['projects']
  in_menu: false
  in_drawer: false
  in_footer: false
  children:
project_with_children:
  text: Projects
  permalink: /what-we-deliver/
  collections: ['projects']
  in_menu: false
  in_drawer: false
  in_footer: false
  children:
    - text: fec-gov
      permalink: /what-we-deliver/fec-gov
      permalink_alt: /what-we-deliver/
      collections: ['projects']
      in_menu: false
      in_drawer: false
      in_footer: false
      children:
