# Commented out for now. Re-enable when the project is ready for it.

#name: Close inactive pull requests
#on:
#  schedule:
#    - cron: 0 0 * * *
#
#jobs:
#  close-pulls:
#    runs-on: ubuntu-latest
#    permissions:
#      pull-requests: write
#    steps:
#      - uses: actions/stale@v4.0.0
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          days-before-issue-stale: -1 # disable making issues stale for now
#          days-before-pr-stale: 30
#          days-before-pr-close: 14
#          stale-pr-label: stale
#          stale-pr-message: >
#            This pull request has been inactive for 30 days. Is it still in
#            progress? If so, please comment, remove the "stale" label, or add
#            new changes. Otherwise, this pull request will be automatically
#            closed in 14 days.
#          close-pr-message: >
#            This pull request has been closed automatically due to inactivity.
